name: RuthlessProgramming
favicon: null
layout_spectrum: 0.9266796191222966
typography_spectrum: 0.29724068148061633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#343434'
    - '#606060'
    - '#aaaaaa'
  brandStrength: 0
  lightness: 0.9830824639648199
  saturation: 0.8277935388032347
  rhythmicContrast: 0.9513619856443256
purpose: []
